site_name: Tronic247 Material
site_url: https://tronic247.github.io/material-docs/
repo_url: https://github.com/Tronic247/material-docs
main_repo_url: https://github.com/Tronic247/material
edit_uri: edit/main/docs/
site_author: Posandu Mapa
copyright: Tronic247

theme:
    name: null
    custom_dir: 'theme'
    static_templates:
        - index.html
        
markdown_extensions:
    toc:
        permalink: true
    admonition: {}
    
nav:
    - Home: index.md
    - Products:
      - Cloud:
        - AWS Marketplace:
          - Rsyslog Server: products/cloud/aws-marketplace/rsyslog-server.md
          - OpenVPN Server: products/cloud/aws-marketplace/openvpn-server.md
        - Azure:
          - Rsyslog Server: products/cloud/azure/rsyslog-server.md
          - OpenVPN Server: products/cloud/azure/openvpn-server.md
      - Hardware:
        - Placeholder: products/hardware/placeholder.md
