site_name: Tronic247 Material
site_url: https://tronic247.com/material/
repo_url: https://github.com/Tronic247/tronic247-material-docs
main_repo_url: https://github.com/Tronic247/material
edit_uri: edit/main/docs/

theme:
    name: null
    custom_dir: 'theme'
    static_templates:
        - index.html